version: "3.1"
nlu:
- intent: bot_challenge
  examples: |
    - am I talking to a human?
    - are you a bot?
    - am I talking to a bot?
- intent: affirm
  examples: |
    - yes
    - y
    - that sounds good
    - of course
    - correct
- intent: deny
  examples: |
    - not really
    - never
    - no way
    - don't like that
    - no
- intent: sofa_challenge
  examples: |
    - sofa?
    - any sofa?
    - do you have a sofa for me?
    - any sofa, please?
    - sofaaaaa
    - i want sofa.
    - where can i find a sofa?
- intent: goodbye
  examples: |
    - see you around
    - good night
    - have a nice day
    - cu
    - cee you later
    - see you later
    - good by
    - bye bye
- intent: don't_understand
  examples: |
    - cell phone
    - trip
    - plane
    - restaurant
    - hmmm
    - car
    - football
    - volleyball
- intent: checking_type1
  examples: |
    - ottoman
    - camelback sofas
    - the Belgian roll arm sofa
    - sofa beds
    - armchair
    - sofas with no arms
    - modular sofa
    - the round arm sofa
- intent: option
  examples: |
    - cheapest
    - best
    - no preferences
    - the cheapest option
    - best option
    - give me the cheapest option
    - whatever you want
    - the best option
    - give me the best option
- intent: checking_type2
  examples: |
    - 5 seats
    - 1 seat
    - 5 seater
    - 3 seater
    - multi seater
    - 1 seater
    - 2 seats
    - multiseater
    - 2 seater
    - 4 seats
    - 4 seater
- intent: money
  examples: |
    - from 100 to 199
    - from 400 to 499
    - from 200 to 299
    - about 500
    - from 500 to 599
    - for free
    - about 400
    - from 0 to 99
    - from 300 to 399
    - about 200
- intent: greet
  examples: |
    - moin
    - hey there
    - hello
    - hi
    - hello there
    - good afternoon
    - goodevening
    - good evening
    - hallo
    - let's go
    - hey dude
- intent: mood_great
  examples: |
    - I am going to save the world
    - feeling like a king
    - I am great
    - I am amazing
    - perfect
    - extremely good
    - so good
    - so perfect
    - I am feeling very good
    - super stoked
    - amazing
- intent: mood_unhappy
  examples: |
    - not very good
    - unhappy
    - I don't feel very well
    - sad
    - I am disappointed
    - not good
    - my day was horrible
    - I'm so sad
    - very sad
    - super sad
    - extremly sad
    - so sad
